---
- name: create a comptatible deployment scripts from oooq
  include: use_oooq.yaml
  tags: use_oooq
  when: use_oooq|bool

- name: create undercloud upgrade script
  template:
    src: "{{ undercloud_upgrade_template }}"
    dest: "{{ undercloud_upgrade_script }}"
    mode: 0775

- name: create upgrade workaround scripts
  template:
    src: workarounds.sh.j2
    dest: "{{working_dir}}/{{ item }}.sh"
    mode: 0775
  with_items:
     - 'pre_undercloud_upgrade_workarounds'
     - 'pre_docker_composable_upgrade_workarounds'
     - 'pre_nova_compute_upgrade_workarounds'
     - 'pre_docker_converge_upgrade_workarounds'
     - 'post_docker_converge_upgrade_workarounds'
  when: upgrade_workarounds

- name: create container images download script
  template:
    src: "{{ container_images_download_template }}"
    dest: "{{ container_images_download_script }}"
    mode: 0775

- name: create registry environment file script
  template:
    src: "{{ local_docker_registry_env_template }}"
    dest: "{{ local_docker_registry_env_script }}"
    mode: 0775

- name: create composable upgrade scripts
  include: step_upgrade.yml
  loop_control:
    loop_var: ugstage
  with_items:
    - step: "Docker containers composable upgrade"
      script: "{{ overcloud_composable_upgrade_script }}"
      environment_file:
        - "{{ tht_directory }}/environments/docker.yaml"
        - "{{ tht_directory }}/environments/docker-ha.yaml"
        - "{{ tht_directory }}/environments/major-upgrade-composable-steps-docker.yaml"
        - "{% if not upstream_container_images or (upstream_container_images and use_local_docker_registry) %}{{ containers_default_parameters }}{% endif %}"
    - step: "Docker containers converge upgrade"
      script: "{{ overcloud_converge_upgrade_script }}"
      environment_file:
        - "{{ tht_directory }}/environments/docker.yaml"
        - "{{ tht_directory }}/environments/docker-ha.yaml"
        - "{{ tht_directory }}/environments/major-upgrade-converge-docker.yaml"
        - "{% if not upstream_container_images or (upstream_container_images and use_local_docker_registry) %}{{ containers_default_parameters }}{% endif %}"

- name: adjust ssh config to skip host key check
  copy:
    src: ssh_config
    dest: "~/.ssh/config"
    mode: 0600

- name: Nova compute nodes upgrade scripts
  include: node_upgrade_script.yml
  with_items: "{{ groups.compute|default([]) }}"
  loop_control:
      loop_var: node_name
