---
- name: run docker upgrade composable step
  shell: |
    source {{ undercloud_rc }}
    bash {{ overcloud_composable_upgrade_script }} &> {{ working_dir }}/overcloud_composable_upgrade.log
  register: overcloud_composable_upgrade
  ignore_errors: yes

- name: print stack failures
  shell: |
    source {{ undercloud_rc }}
    openstack stack failures list overcloud
  when: overcloud_composable_upgrade.rc != 0

- fail: msg="Overcloud upgrade composable step failed... :("
  when: overcloud_composable_upgrade.rc != 0
