---
- name: run setup heat outputs script
  shell: |
    source {{ undercloud_rc }}
    bash {{ heat_outputs_upgrade_script }} &> {{ working_dir }}/overcloud_heat_outputs_upgrade.log
  register: overcloud_heat_outputs_upgrade
  ignore_errors: yes

- name: print stack failures
  shell: |
    source {{ undercloud_rc }}
    openstack stack failures list overcloud --long
  when: overcloud_heat_outputs_upgrade.rc != 0

- fail: msg="Overcloud upgrade setup heat outputs step failed... :("
  when: overcloud_heat_outputs_upgrade.rc != 0
