---
- name: create undercloud update script
  template:
    src: "{{ undercloud_update_template }}"
    dest: "{{ undercloud_update_script }}"
    mode: 0775

- name: create scripts with workarounds
  template:
    src: "{{ update_workarounds_template }}"
    dest: "{{ working_dir }}/{{ item.script }}"
    mode: 0755
  with_items:
    - '{{ pre_undercloud_update_workarounds|default([]) }}'
    - '{{ post_undercloud_update_workarounds|default([]) }}'
    - '{{ pre_overcloud_update_workarounds|default([]) }}'
    - '{{ post_overcloud_update_workarounds|default([]) }}'
  when: updates_workarounds|bool


- name: create overcloud update setup script
  template:
    src: "{{ overcloud_update_setup_template }}"
    dest: "{{ overcloud_update_setup_script }}"
    mode: 0775

- name: create overcloud update script
  template:
    src: "{{ overcloud_update_template }}"
    dest: "{{ overcloud_update_script }}"
    mode: 0775
